services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    working_dir: /app/app
    volumes:
      - ./app:/app/app

    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring


networks:
  monitoring:
    driver: bridge
